version: "3.8"

services:
  postgres:
    build: ./database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
  app:
    build: ./client
    command: sh -c "npm install && npm run dev"
    working_dir: /usr/src/app/client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
      - /usr/src/app/client/.next
    ports:
      - 3000:3000
  api:
    build: ./api
    command: sh -c "npm install --also=dev && npm run dev"
    working_dir: /usr/src/app/api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    ports:
      - 5000:5000
    depends_on:
      - postgres

  # api:
  #   build: ./api
  #   working_dir: /app/api
  #   volumes:
  #     - ./api:/app/api
  #   depends_on:
  #     - postgres
