version: "3.8"

services:
  postgres:
    build: ./database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
  app:
    build: ./client
    working_dir: /usr/src/app/client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
      - /usr/src/app/client/.next
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: ["/usr/src/app/client/wait-for.sh", "postgres", "npm", "run", "dev"]