version: "3.8"

services:
  postgres:
    build: ./database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=user_db
  app:
    build: ./client
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules
      - /usr/app/client/.next
    ports:
      - 3000:3000
    depends_on:
      - postgres
volumes:
  data:
